import { useEffect, useRef, useState } from "react";
import useAIEnabled from "./useAIEnabled";
import { api } from "./lib";
import { ChevronRight, ChevronDown, Sparkles, Copy, Activity, ShieldAlert, Layers3 } from "lucide-react";
import { formatPacketDateTime, formatPacketTime, systemTimeZone } from "./time";

const DETAIL_TABS = ["Summary", "Layers", "Connection", "Protocol", "TCP Health", "Hex", "Security", "Explain"];

export default function PacketAnalyzer({ packets, selected, setSelected, status, onFollowFlow }) {
  return <div className="grid grid-cols-1 lg:grid-cols-12 gap-4">
    <div className="lg:col-span-7 bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 overflow-hidden flex flex-col" style={{height:"calc(100vh - 260px)"}}>
      <div className="px-4 py-2.5 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between"><div><h3 className="font-display font-bold text-sm">Packet Stream</h3><div className="text-[10px] text-slate-500">Time shown in {systemTimeZone()}</div></div><div className="flex items-center gap-2">{selected && ["TCP","HTTP","HTTPS","SSH","TLS","FTP","SMTP"].includes(selected.protocol) && selected.src_port && selected.dst_port && <button onClick={()=>follow(selected,onFollowFlow)} className="text-xs px-2 py-1 rounded-md bg-blue-600 hover:bg-blue-700 text-white font-semibold">Follow flow</button>}<span className="text-xs text-slate-500 font-mono-code">{packets.length} packets</span></div></div>
      <PacketTable packets={packets} selected={selected} onSelect={setSelected}/>
    </div>
    <div className="lg:col-span-5" style={{height:"calc(100vh - 260px)"}}><DeepInspector packet={selected} onFollowFlow={onFollowFlow}/></div>
  </div>;
}

function follow(p,cb){const [a_ip,a_port,b_ip,b_port]=(p.src_ip<p.dst_ip||(p.src_ip===p.dst_ip&&p.src_port<p.dst_port))?[p.src_ip,p.src_port,p.dst_ip,p.dst_port]:[p.dst_ip,p.dst_port,p.src_ip,p.src_port];cb?.({a_ip,a_port,b_ip,b_port,protocols:[p.protocol],packets:0});}

function PacketTable({packets,selected,onSelect}){return <div className="flex-1 overflow-auto el-scroll"><table className="w-full text-xs"><thead className="sticky top-0 bg-slate-50 dark:bg-slate-800/90 z-10"><tr className="text-left text-slate-500 uppercase tracking-wider text-[10px]"><th className="px-3 py-2">#</th><th className="px-3 py-2">Local time</th><th className="px-3 py-2">Source</th><th className="px-3 py-2">Destination</th><th className="px-3 py-2">Proto</th><th className="px-3 py-2 text-right">Len</th><th className="px-3 py-2">Info</th></tr></thead><tbody className="font-mono-code">{!packets.length&&<tr><td colSpan={7} className="text-center text-slate-400 py-12 text-sm">No packets yet. Start capture or upload a PCAP.</td></tr>}{packets.map(p=><tr key={p.id} onClick={()=>onSelect(p)} className={`border-t border-slate-100 dark:border-slate-800 cursor-pointer hover:bg-slate-50 dark:hover:bg-slate-800/50 ${selected?.id===p.id?"bg-blue-50 dark:bg-blue-500/10":""}`}><td className="px-3 py-1.5 text-slate-400">{p.number}</td><td className="px-3 py-1.5 whitespace-nowrap" title={p.timestamp_iso||"UTC capture timestamp unavailable"}>{formatPacketTime(p.timestamp)}</td><td className="px-3 py-1.5 whitespace-nowrap">{p.src_ip}{p.src_port?`:${p.src_port}`:""}</td><td className="px-3 py-1.5 whitespace-nowrap">{p.dst_ip}{p.dst_port?`:${p.dst_port}`:""}</td><td className="px-3 py-1.5"><span className={`proto-badge proto-${p.protocol}`}>{p.protocol}</span></td><td className="px-3 py-1.5 text-right text-slate-500">{p.length}</td><td className="px-3 py-1.5 truncate max-w-[260px]">{p.info}</td></tr>)}</tbody></table></div>}

function DeepInspector({packet,onFollowFlow}){
 const aiEnabled=useAIEnabled();
 const [detail,setDetail]=useState(null),[tab,setTab]=useState("Summary");
 useEffect(()=>{setTab("Summary");if(!packet){setDetail(null);return;}api.get(`/packets/${packet.id}`).then(r=>setDetail(r.data)).catch(()=>setDetail(packet));},[packet]);
 if(!packet)return <EmptyBlock title="Deep Packet Inspector" message="Select a packet to inspect protocol layers, connection context, health, raw bytes and security context."/>;
 const d=detail||packet;
 return <div className="h-full bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 overflow-hidden flex flex-col">
   <div className="px-4 py-2.5 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between"><div><h3 className="font-display font-bold text-sm">Deep Packet Inspector</h3><div className="text-[10px] text-slate-500 font-mono-code">Packet #{d.number} · {d.protocol} · {d.length} bytes</div></div>{d.src_port&&d.dst_port&&<button onClick={()=>follow(d,onFollowFlow)} className="text-xs px-2 py-1 rounded bg-blue-600 text-white">Connection</button>}</div>
   <div className="flex gap-1 px-2 py-2 border-b border-slate-200 dark:border-slate-800 overflow-x-auto el-scroll">{DETAIL_TABS.filter(t=>t!=="Explain"||aiEnabled).map(t=><button key={t} onClick={()=>setTab(t)} className={`whitespace-nowrap px-2.5 py-1.5 rounded-md text-[11px] font-semibold ${tab===t?"bg-slate-900 dark:bg-blue-600 text-white":"text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800"}`}>{t}</button>)}</div>
   <div className="flex-1 overflow-auto el-scroll p-3">{tab==="Summary"&&<Summary d={d}/>} {tab==="Layers"&&<Layers d={d}/>} {tab==="Connection"&&<Connection d={d}/>} {tab==="Protocol"&&<Protocol d={d}/>} {tab==="TCP Health"&&<TcpHealth d={d}/>} {tab==="Hex"&&<Hex d={d}/>} {tab==="Security"&&<Security d={d}/>} {tab==="Explain"&&aiEnabled&&<AIExplain packet={d}/>}</div>
 </div>
}

function Summary({d}){return <div className="space-y-3"><div className="grid grid-cols-2 gap-2"><Card label="Source" value={`${d.src_ip||"—"}${d.src_port?`:${d.src_port}`:""}`}/><Card label="Destination" value={`${d.dst_ip||"—"}${d.dst_port?`:${d.dst_port}`:""}`}/><Card label="Protocol" value={d.protocol}/><Card label="Length" value={`${d.length||0} bytes`}/><Card label={`Timestamp · ${systemTimeZone()}`} value={formatPacketDateTime(d.timestamp)}/><Card label="Payload" value={`${d.payload_size||0} bytes`}/></div><Section title="Packet information"><KV k="UTC capture time" v={d.timestamp_iso}/><KV k="Info" v={d.info}/><KV k="Flags" v={fmt(d.flags)}/><KV k="TCP health" v={fmt(d.tcp_health)}/></Section></div>}
function Layers({d}){const [open,setOpen]=useState({});return <div className="space-y-1">{(d.layers||[]).map((l,i)=><div key={i} className="rounded-md border border-slate-200 dark:border-slate-800"><button onClick={()=>setOpen(o=>({...o,[i]:!o[i]}))} className="w-full flex items-center gap-2 p-2 text-left">{open[i]===false?<ChevronRight size={14}/>:<ChevronDown size={14}/>}<Layers3 size={13}/><b className="text-xs">{l.name}</b></button>{open[i]!==false&&<div className="px-4 pb-3">{Object.entries(l.fields||{}).map(([k,v])=><KV key={k} k={k} v={fmt(v)}/>)}</div>}</div>)}</div>}
function Connection({d}){return <div className="space-y-3"><Section title="Conversation endpoints"><KV k="Client / source" v={`${d.src_ip||"—"}${d.src_port?`:${d.src_port}`:""}`}/><KV k="Server / destination" v={`${d.dst_ip||"—"}${d.dst_port?`:${d.dst_port}`:""}`}/><KV k="Transport" v={d.protocol}/></Section><Section title="TCP context"><KV k="Sequence" v={pick(d,"tcp_seq","sequence")}/><KV k="Acknowledgement" v={pick(d,"tcp_ack","acknowledgement")}/><KV k="Flags" v={fmt(d.flags)}/><KV k="Window" v={pick(d,"tcp_window","window")}/></Section><p className="text-xs text-slate-500">Use Follow flow / Connection to open the complete bidirectional conversation.</p></div>}
function Protocol({d}){const names=(d.layers||[]).map(x=>x.name);return <div className="space-y-3"><Section title="Observed protocol stack"><div className="flex flex-wrap gap-2">{names.map(n=><span key={n} className="px-2 py-1 rounded bg-blue-50 dark:bg-blue-500/10 text-blue-600 text-xs font-semibold">{n}</span>)}</div></Section>{(d.layers||[]).filter(x=>["DNS","HTTP","HTTPRequest","HTTPResponse","TLS","HTTPS"].some(n=>String(x.name).includes(n))).map((l,i)=><Section key={i} title={l.name}>{Object.entries(l.fields||{}).map(([k,v])=><KV key={k} k={k} v={fmt(v)}/>)}</Section>)}{!names.some(n=>/DNS|HTTP|TLS|HTTPS/.test(n))&&<div className="text-sm text-slate-400 py-8 text-center">No DNS / HTTP / TLS application metadata in this packet.</div>}</div>}
function TcpHealth({d}){const h=d.tcp_health||{};const entries=Object.entries(h);return <div><div className="flex items-center gap-2 mb-3"><Activity size={15}/><b className="text-sm">TCP Health Signals</b></div>{entries.length?<div className="space-y-2">{entries.map(([k,v])=><div key={k} className="flex justify-between rounded-md border border-slate-200 dark:border-slate-800 p-2 text-xs"><span>{k.replaceAll("_"," ")}</span><b className={v?"text-amber-500":"text-emerald-500"}>{fmt(v)}</b></div>)}</div>:<div className="text-sm text-slate-400 py-8 text-center">No TCP health anomaly is attached to this packet.</div>}</div>}
function Security({d}){const h=d.tcp_health||{};const findings=[];if(h.reset)findings.push("TCP connection reset observed");if(h.retransmission)findings.push("Retransmission detected");if(h.zero_window)findings.push("TCP zero-window condition");if(h.out_of_order)findings.push("Out-of-order TCP segment");return <div><div className="flex items-center gap-2 mb-3"><ShieldAlert size={15}/><b className="text-sm">Packet Security Context</b></div>{findings.length?findings.map(x=><div key={x} className="mb-2 rounded-md border border-amber-200 dark:border-amber-500/30 bg-amber-50 dark:bg-amber-500/10 p-3 text-xs">{x}</div>):<div className="rounded-md border border-emerald-200 dark:border-emerald-500/30 bg-emerald-50 dark:bg-emerald-500/10 p-3 text-xs">No packet-level security or TCP-health warning currently attached. This does not by itself mean the traffic is safe.</div>}</div>}
function Hex({d}){const hex=d.hex||"",bytes=[];for(let i=0;i<hex.length;i+=2)bytes.push(hex.slice(i,i+2));const rows=[];for(let i=0;i<bytes.length;i+=16)rows.push(bytes.slice(i,i+16));return <div><div className="flex justify-between mb-2"><span className="text-xs text-slate-500">Raw packet bytes</span><button onClick={()=>navigator.clipboard?.writeText(hex)} className="text-xs inline-flex items-center gap-1"><Copy size={12}/>copy</button></div><div className="font-mono-code text-[11px]">{rows.map((r,i)=><div key={i} className="flex gap-3 whitespace-pre"><span className="text-slate-400">{(i*16).toString(16).padStart(4,"0")}</span><span className="flex-1">{r.join(" ")}</span><span className="text-slate-500">{r.map(b=>{const c=parseInt(b,16);return c>=32&&c<=126?String.fromCharCode(c):"."}).join("")}</span></div>)}{!rows.length&&<div className="text-slate-400">No raw bytes available.</div>}</div></div>}

function AIExplain({packet}){const [text,setText]=useState(""),[loading,setLoading]=useState(false);const abortRef=useRef(null);useEffect(()=>setText(""),[packet?.id]);const explain=async()=>{setText("");setLoading(true);const ctrl=new AbortController();abortRef.current=ctrl;try{const resp=await fetch(`${api.defaults.baseURL}/ai/explain`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({packet_id:packet.id}),signal:ctrl.signal});if(!resp.ok)throw new Error(`HTTP ${resp.status}`);const reader=resp.body.getReader(),decoder=new TextDecoder();let buf="";while(true){const {value,done}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});let idx;while((idx=buf.indexOf("\n\n"))!==-1){const chunk=buf.slice(0,idx);buf=buf.slice(idx+2);if(!chunk.startsWith("data:"))continue;const payload=chunk.slice(5).trim();if(payload==="[DONE]")break;try{const o=JSON.parse(payload);if(o.delta)setText(t=>t+o.delta)}catch(_){}}}}catch(e){if(e.name!=="AbortError")setText(`[error: ${e.message}]`)}finally{setLoading(false)}};return <div className="rounded-xl border border-indigo-200 dark:border-indigo-500/30 overflow-hidden"><div className="p-3 flex items-center justify-between border-b border-indigo-100 dark:border-indigo-500/20"><b className="text-sm flex gap-2 items-center"><Sparkles size={14}/>Explain Packet</b><button onClick={explain} disabled={loading} className="px-2.5 py-1 rounded bg-indigo-600 text-white text-xs">{loading?"Analyzing…":"Explain"}</button></div><div className="p-3 text-sm whitespace-pre-wrap min-h-32">{text||<span className="text-slate-400">Generate a contextual explanation using packet, protocol, connection and health metadata.</span>}</div></div>}

function Card({label,value}){return <div className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><div className="text-[10px] uppercase tracking-wider text-slate-500">{label}</div><div className="mt-1 text-xs font-mono-code break-all">{value||"—"}</div></div>}
function Section({title,children}){return <div className="rounded-lg border border-slate-200 dark:border-slate-800 p-3"><div className="text-xs font-bold mb-2">{title}</div>{children}</div>}
function KV({k,v}){return <div className="grid grid-cols-[120px_1fr] gap-2 py-1 text-[11px] font-mono-code"><span className="text-slate-500 break-all">{k}</span><span className="break-all">{v===undefined||v===null||v===""?"—":String(v)}</span></div>}
function EmptyBlock({title,message}){return <div className="h-full rounded-xl border border-dashed border-slate-300 dark:border-slate-700 flex items-center justify-center p-8 text-center"><div><div className="font-bold mb-1">{title}</div><div className="text-sm text-slate-400">{message}</div></div></div>}
function fmt(v){if(v===undefined||v===null||v==="")return "—";if(typeof v==="object")return JSON.stringify(v);return String(v)}
function pick(obj,...keys){for(const k of keys)if(obj?.[k]!==undefined&&obj?.[k]!==null)return obj[k];return "—"}
